---
- include: repositories.yml
  when: os_family == "debian"

- include: packages.yml
  become: true
- include: ufw.yml
  become: true
  tags:
    - firewall
  when: "disable_ufw == 'false'"
- include: user.yml
  become: true
- include: ruby.yml
  become: true
  become_user: mastodon
- include: mastodon.yml
  become: true
  become_user: mastodon
- include: letsencrypt.yml
  become: true
  tags:
    - letsencrypt 
  when: "disable_letsencrypt == 'false' and disable_nginx == 'false'"
- include: nginx.yml
  become: true
  when: "disable_nginx == 'false'"
